version: '3.8'

services:
  postgres:
    image: postgres:13.1-alpine
    ports:
      - "15432:5432"
    environment:
      - POSTGRES_USER=compose-postgres
      - POSTGRES_PASSWORD=compose-postgres
      - POSTGRES_DB=postgres
    volumes:
      - "db-data:/var/lib/postgresql/data"
  app:
    image: 'app'
    build:
      context: .
    command: java -jar ./app.jar
    ports:
      - "8080:8080"
    depends_on:
      - postgres
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://postgres/postgres
volumes:
  db-data: {}