spring:
  datasource:
    url: ${SPRING_DATASOURCE_URL:jdbc:postgresql://localhost:15432/postgres}
    username: compose-postgres
    password: compose-postgres
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
bot:
  name: BoomerangMoney_bot
  token: ${BOOMERANG_BOT_TOKEN}
